name = "heimish-contacts"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "CONTACTS_BUCKET"
bucket_name = "heimish-contacts"

[vars]
ADMIN_TOKEN = "hm_admin_avrumy_2024"
